### ISSUE TITLE
Duplicate Language key with a lot of mod

### ISSUE THREAD

**Issue by TartaricAcid** [Kashdeya/Tiny-Progressions#103]
`item.silver_dust.name`
- primal: `Silver Dust`
- tp: `LightGray Glowstone Dust`

`item.pouch.name`
- roots: `Powder Pouch`
- tp: `Big Pouch`

`tile.flesh_block.name`
- thaumcraft: `Block of Flesh`
- tp: `Compressed Flesh Block`

**Comment by GenDeathrow** [comment]
Hey thanks @TartaricAcid, I'l take this on a update after this next one.
