### ISSUE TITLE
Wub hammer and enchants

### ISSUE THREAD

**Issue by jinkhya** [Kashdeya/Tiny-Progressions#107]
Pack : Foolcraft 3
Tiny progressions : tinyprogressions-1.12.2-3.3.29-Release.jar
forge : 1.12 2705

Hello, 

It looks like adding enchants to the wub hammer doesn't do anything. I tried fortune III and smelting (from cofh) and they don't work. It works fine on the wub pickaxe though.

**Comment by SephirothWS** [comment]
Tiny Progressions: tineprogressions-1.12.2-3.3.32-Release.jar
Forge: forge-14.23.5.2796

I can confirm the Wub Hammer ignores enchantments.

![image](https://user-images.githubusercontent.com/9165737/60259759-95ade600-989d-11e9-8f97-e8483331392f.png)
This silk touch hammer still gives me cobblestone when I mine stone.
![image](https://user-images.githubusercontent.com/9165737/60259800-ae1e0080-989d-11e9-94a2-220e16ed768c.png)
![image](https://user-images.githubusercontent.com/9165737/60259816-b70ed200-989d-11e9-8a73-da9da18e73a2.png)

**Comment by GenDeathrow** [comment]
I look thur the code see whats up. This wasn't my original mod. And for the most part I have left most as it was unless its an obvious bug. Thanks for the report.
