### ISSUE TITLE
[1.12.2] Pls make the view in JEI great again!

### ISSUE THREAD

**Issue by TheSnowyChickens** [Kashdeya/Tiny-Progressions#109]
Hello,

your mod has a rly confused JEI view.
![grafik](https://user-images.githubusercontent.com/29357962/44693346-90a6bd00-aa67-11e8-82dd-a4f6b52e7fe6.png)
Can you pls do something, so that it look more cleaned up and sorted?
Thx xD

1.12.2
Forge 2747
TP 3.2.26

**Comment by BugmanBugman** [comment]
Agreed
