### ISSUE TITLE
Wub hammer causing crash

### ISSUE THREAD

**Issue by lolipopopoop** [Kashdeya/Tiny-Progressions#110]
I'm Playing Foolcraft 3 And the game crashes when I use the Wub Hammer

Crash Report:
https://paste.dimdev.org/jejoqamiju.mccrash

When I hit an enderman the game thinks it's destroying a block and crashes.

**Comment by itanshi** [comment]
https://paste.dimdev.org/isupinavem.mccrash same, wither cat

**Comment by GenDeathrow** [comment]
pretty sure its related to another issue.
