### ISSUE TITLE
Enchantment Table clear out Inventory

### ISSUE THREAD

**Issue by Kratzwurst** [Kashdeya/Tiny-Progressions#114]
Hello all

I Crafting the Bag Pouch and i want it to Soulbound Entchantment on this Bag. 
After this attempt, i show in the Bag and i lost the Bag Invetory directly.

## Steps to Reproduce (for bugs)

1. Creating the Bag Pouch
2. Fill up with Items
3. All Items to see
3. Want it to Enchantment Soulbound
4. See it does not work
5. Look in the Bag and lost all Items in this Bag Pouch
6. Same without Lapis.
## Logs
[latest.log](https://github.com/Sunekaer/stoneBlock/files/2452647/latest.log)

## Client Information

* Modpack Version: Stoneblock 1.0.17
* Mod Version:  tinyprogressions-1.12.2.-.3.3.3.1
* Server/LAN/Single Player: SP
* Optifine Installed: YES OptiFine_1.12.2_HD_U_E2
* Shaders Enabled: NO

Greetings

**Comment by GenDeathrow** [comment]
Seems like its a vanilla issue. I will look at it.
