### ISSUE TITLE
There is a lot of z fighting on the growth crystals

### ISSUE THREAD

**Issue by JBSTheGamer** [Kashdeya/Tiny-Progressions#117]
If you were to look at the growth crystals from a distance like this then the growth crystals will z fight like crazy. Like seen below.
![1 8 0_51 2018 12 03 - 12 17 48 05-0-1-1543868303818 1](https://user-images.githubusercontent.com/32559193/49393206-7a9f3d00-f6e5-11e8-8a15-17632aa0b072.gif)

**Comment by GenDeathrow** [comment]
Cant seem to replicate it. You using any mods that mess with rendering
