### ISSUE TITLE
Wub Hammer can cause crash when ore excavating

### ISSUE THREAD

**Issue by Sunekaer** [Kashdeya/Tiny-Progressions#120]
Wub Hammer can cause crash when ore excavating

https://paste.feed-the-beast.com/view/raw/3c8e5aa4
https://paste.feed-the-beast.com/view/8e9f36f9

**Comment by Slyklaw** [comment]
The bug can be reproduced by moving out of range right as the block is broken. This happens even on single player without excavation.

"result" is dereferenced without being tested for null.

https://github.com/Kashdeya/Tiny-Progressions/blob/1.12.2/src/main/java/com/kashdeya/tinyprogressions/items/tools/wub/WubHammer.java#L46
