### ISSUE TITLE
Item Dupe between Tinkers Toolstation and Any Cobble Gen.

### ISSUE THREAD

**Issue by ghost** [Kashdeya/Tiny-Progressions#123]
Heres a video one of my server members made for me.
https://www.youtube.com/watch?v=ZQfs4yuwLWE

FIX: remove interaction or inventory slot from cobble gen!

Works for anypack with Tiny Progression and tinkers.

**Comment by GenDeathrow** [comment]
How did he even come up with that.

**Comment by ghost** [comment]
accident.  lol..

**Comment by GenDeathrow** [comment]
Crap, strange thing. Inputting items is turned off for that block So that shouldn't happen at all.

**Comment by ghost** [comment]
well the interaction is weird. i guess it some how can get fixed by removing the inventory slot some how? 
since right now im personally blocking with with blacklisting it in tinkers configs. tho im sure there is probally otherways of doing this too in other mods. tho i got no time to test that out hehe.

**Comment by GenDeathrow** [comment]
Well removing the slot can have some unforeseen issues with breaking with other inventories it interacts with. but I will see if I can figure this out. Bigger issue is it looks like jei is ignoring the slots permissions, but I need to confirm my side is working properly first.

**Comment by GenDeathrow** [comment]
Simple fix.. I just be deleting anything that isn't cobble from now on.

**Comment by ghost** [comment]
Yey new Trash can with cobble stone filter wait what? :D hehe

**Comment by GenDeathrow** [comment]
Update should be coming. Contact me if you get any issues.
