### ISSUE TITLE
Can't craft flint tools or weapon - just become stone items

### ISSUE THREAD

**Issue by AbieTheFishman** [Kashdeya/Tiny-Progressions#125]
Crafting with flint of any tools or weapon results in a stone tool or weapon

**Comment by GenDeathrow** [comment]
Is this part of a mod pack? I just tested this. Everything works as intended. If its a modpack make sure to report it to the dev.

![image](https://user-images.githubusercontent.com/3720710/52247326-19474600-28af-11e9-8e03-b5cb94f19feb.png)
