### ISSUE TITLE
Crash log after adding this mod

### ISSUE THREAD

**Issue by ValskraaCapo** [Kashdeya/Tiny-Progressions#127]
https://gist.github.com/GenDeathrow/65a77a5107e39523cffd4ba56dd787f1

**Comment by GenDeathrow** [comment]
Ok for the error its not my mod that's showing the crash, but Modular ForceField System. I would report to them first. See if they know what causes the error.  If its a mod interaction crash of some sorts.. than we can work together. At the moment it shows them crashing and dealing with cofh api.  

Also you didn't say what caused the crash. 
Is it a loading issue or were you doing anything at the time of the crash?
I'm guessing it was a loading issue.

**Comment by ValskraaCapo** [comment]
Yes it happened on loading screen when initalizing the game. i can try to send it too modular forcefield system team!

**Comment by GenDeathrow** [comment]
I just checked them out.. seems they have had issues with other mods causing crashes.. so Im going to think this isn't a TP issue but an MFFS issue. So Im closing this for now until otherwise known.
