### ISSUE TITLE
[Enhancement] Ability to turn cobble gen on or off with redstone signal

### ISSUE THREAD

**Issue by addrever** [Kashdeya/Tiny-Progressions#13]
Hello....

This is a great mod and appreciate the work you have put into it.

I was thinking that it might be a cool idea if you could turn the cobble generation on and off depending on the state of a redstone signal.

**Comment by Kashdeya** [comment]
why would you need to turn it off or on? I do not understand. it turns off when the internal inventory is full or the storage it is connected to is. So what is the purpose of using a redstone signal?

**Comment by addrever** [comment]
Why not?  Maybe someone wants it turned off or on when the cobble goes below or above a certain threshold.

I'm sorry if my question offended you.  Your words come across as being somewhat annoyed.

**Comment by addrever** [comment]
Thinking about this there are a lot of ways to make this work without having the redstone on the actual cobble gen.  I was just throwing it out there so that there is the option.

Cheers.

**Comment by Kashdeya** [comment]
Don't be sorry, You did not offend me what so every, I just do not see a reason to add redstone signal to the block. The block is meant for a skyblock style modpack and you need every bit of cobblestone you can get in that type of gameplay and the way I have the tiers coded with the internal inventory it all balances out in the end.
