### ISSUE TITLE
Using Pouch to Reproduce Items Infinitely

### ISSUE THREAD

**Issue by PIPILAN** [Kashdeya/Tiny-Progressions#131]
First I put the items I want to brush into the pouch and keep the bag interface open. Then I throw the bag out with the Q key. I take the items out of the interface. Then I pick up the bag. You will find another item in the bag.

**Comment by GenDeathrow** [comment]
alright sounds reproducible. Can you make sure to add in the version numbers of the mod and minecraft please.  Its just good for reference.

**Comment by PIPILAN** [comment]
My game version is 1.12.2 and my mod version is tinyprogressions-1.12.2-3.3.32-Release.
