### ISSUE TITLE
Crash at World load

### ISSUE THREAD

**Issue by Ravalli03** [Kashdeya/Tiny-Progressions#134]
Every time I try to load my world, it crashes. It was running fine until I changed some configs to not allow ore gen, not sure what is causing it.

https://pastebin.com/DmCfr54Y

Thanks for the help

**Comment by GenDeathrow** [comment]
Yeah thats cause it generated stuff, but now you tried to remove it and it crashes. youd have to start a new world to remove world gen.

**Comment by Ravalli03** [comment]
oh that sucks, thanks for the quick help.
