### ISSUE TITLE
Console spam: [com.kashdeya.tinyprogressions.tiles.TileEntityCobblegen:func_73660_a:88]: Full

### ISSUE THREAD

**Issue by NLBlacky** [Kashdeya/Tiny-Progressions#135]
Our console is being spammed by the following lines:
[com.kashdeya.tinyprogressions.tiles.TileEntityCobblegen:func_73660_a:88]: Full

We're running Stoneblock 2 with TinyProgression version tinyprogressions-1.12.2-3.3.32-Release.jar

Logs: https://file.io/dPe66K
![image](https://user-images.githubusercontent.com/42154364/58996694-a23ca280-87f9-11e9-979f-52bd6c960964.png)

I would like to know if anyone else is having this issue and managed to fix it?
No coords are given so we're having a hard time finding the source in our multiplayer server.

**Comment by GenDeathrow** [comment]
Its a printout.. not sure why its there.. but its removed and in fix in 3.3.33
