### ISSUE TITLE
updated to 3.3.33 hotfix and mod dissapears from game even though in mod folder

### ISSUE THREAD

**Issue by raziel23x** [Kashdeya/Tiny-Progressions#136]
updated to the 6/6/19 update and now the entire mod vanished and when i do @tiny in the jei nothing shows up and also all cobblestone generators i had placed are all gone and the mod is acting like it is not installed but as soon as i revert back to previous version everything is back again

**Comment by GenDeathrow** [comment]
Some how the incorrect file was uploaded Fixing now
