### ISSUE TITLE
Big Pouch is voiding inventory

### ISSUE THREAD

**Issue by SummitSummit** [Kashdeya/Tiny-Progressions#139]
I haven't found out why it happens, it is inconsistent, but the Big Pouch is sometimes completely empty when I start the world.  It is voiding my stuff. 

Version tinyprogressions-1.12.2-3.3.34-Release

In the Antimatter Chemistry modPack version 1.2.13

**Comment by GenDeathrow** [comment]
single or server?

**Comment by SummitSummit** [comment]
Single.

**Comment by GenDeathrow** [comment]
It may be a while before I can get to this. I have a lot queued up atm. But if I can figure this out I'll do my best. Thanks for reporting.

**Comment by semirotta** [comment]
I have this on server and I lost so much stuff because I used your Pouch -.-'' I didn't notice it was deleting my items constantly.

Is there going to be a fix any time soon or can you completely remove the pouch or other carry-on thing that causes items to be deleted like that?
