### ISSUE TITLE
Party Pickaxe ExU2 Bug (1.0.17, 1.10.2)

### ISSUE THREAD

**Issue by SweetSugarSugar** [Kashdeya/Tiny-Progressions#15]
When using the Mechanical User from Extra Utilities 2 set on "Use Item on Block" with the Party Pickaxe, it will replace blocks in front of the Mechanical User (including bedrock).

**Comment by Kashdeya** [comment]
I do not know why this is happening. I have the pickaxe checking blocks to see if they are replacable or not. Let me see if I can figure something out.

**Comment by Kashdeya** [comment]
fixed
