### ISSUE TITLE
Server crashes on 1.15.2

### ISSUE THREAD

**Issue by apocalypse3000** [Kashdeya/Tiny-Progressions#151]
Anytime I try to start a server, it crashes. Client works fine with other 59 mods. First I tried to start a server with about 50 mods, but it kept crashing. Then I tried to launch it with only Tiny Progressions 4.0.0 but problem still persists. Here's a log. https://pastebin.com/XriSy3xW

**Comment by GenDeathrow** [comment]
Thank you for the report. I will take a look at it. This is beta so I was expecting bugs.. just thought server bugs were fixed.

**Comment by Pythonic-Rainbow** [comment]
So is this fixed?

**Comment by GenDeathrow** [comment]
The block that originally caused the issue is still not fixed atm. That's why it was removed from game for now.

**Comment by Pythonic-Rainbow** [comment]
ok
