### ISSUE TITLE
Game crash between Tiny Progressions and Packed Up (Backpacks)

### ISSUE THREAD

**Issue by GillianGroks** [Kashdeya/Tiny-Progressions#154]
Minecraft Version: 1.15.2 
Tiny Progressions version: tinyprogressions-1.15.2-4.0.1.jar
Packed Up version: packedup-1.0.12-mc1.15.jar

Steps to reproduce:

1. Create Modpack with Tiny Progressions and Packed Up (Backpacks)
2. Load Game
3. Try to load into a world
4. Game Crashes with Error Message:
     The game crashed whilst ticking memory connection
     Error: java.lang.RuntimeException: Why did the advancements not load yet?!

I am also submitting this report to SuperMarijin642 (Packed Up developer)

Crash Report:
[https://pastebin.com/NMPLG5di](url)

**Comment by GenDeathrow** [comment]
I'm fairly certain this has to do with a recipe I had that should only work if copper ingot was added to a forge tag. I noticed Packed up also does this. I have tried something to see if it will fix it. Update will probably come out some time tomorrow. I will be testing this version with packed up soonish.

**Comment by GenDeathrow** [comment]
I think this has something to do with the new Tag system that replaced the OreDict system. I am still learning it all. I think it has to do with a alternative recipe that uses copper. I don't have copper on my mod.. but I think its cause I didn't register it properly ..... I think. Still trying to figure them all out. 

Edit: I did get it to work with your mod in my dev enviroment.. just hadn't pushed the update yet.
