### ISSUE TITLE
Tiny Progressions 1.15.2-4.0.1 crashes SP world

### ISSUE THREAD

**Issue by ClaudiusMinimus** [Kashdeya/Tiny-Progressions#155]
When I add Tiny Progressions 1.15.2-4.0.1 to my mod pack I am developing, the client crashes upon loading a new world. When I disable Tiny Progressions the world loads normally.

OS: Linux Mint 19.3
Minecraft 1.15.2
Forge version: 31.2.0
Java: Oracle Java 1.8.0_212
Tiny Progressions: 1.15.2-4.0.1 

https://paste.ee/p/csJ0e

**Comment by zackeezy** [comment]
Can confirm, I am experiencing the same issue.

OS: Ubuntu 20.04
Minecraft: 1.15.2
Forge Version: 31.2.5

https://pastebin.com/49gG4cQP

**Comment by Esheon** [comment]
Same

Win10
MC 1.15.2
Forge 31.2.5

https://pastebin.com/FqkcWpCa

**Comment by GenDeathrow** [comment]
Sorry been busy this last week. I think I have a fix sitting on my dev version already. was meaning to get it out this week end. Will try to get this out later tonight.

**Comment by ClaudiusMinimus** [comment]
So far everything seems to work great! Thanks
