### ISSUE TITLE
[1.15] Mod really broken

### ISSUE THREAD

**Issue by BedrockLegends** [Kashdeya/Tiny-Progressions#157]
![2020-05-31_17 36 11](https://user-images.githubusercontent.com/48525410/83364210-4ef62500-a365-11ea-9cd6-932ba5d14bfa.png)
 That screenshot is logging into a server on the new recommended version of forge

**Comment by GenDeathrow** [comment]
https://github.com/Kashdeya/Tiny-Progressions/issues/158
