### ISSUE TITLE
[1.15] issue logging into server

### ISSUE THREAD

**Issue by IchigoGames** [Kashdeya/Tiny-Progressions#158]
some one reported this with just a pic and saying it broken so if you want to close this you can but i thought more info might be helpful 

Minecraft 1.15.2
Forge 31.2.0
tinyprogressions-1.15.2-4.0.2

logs
[logs.zip](https://github.com/Kashdeya/Tiny-Progressions/files/4714375/logs.zip)
![Capture](https://user-images.githubusercontent.com/11888162/83472822-bbe4ea00-a44d-11ea-9ab5-29f5e3146465.PNG)

**Comment by GenDeathrow** [comment]
Hey appreciate it. Sorry for the long response.. I work longer hours during the summer time. So I rarely get on during the week. Didn't realize forge came out with a new version. I take a look at it as soon as I can. Thanks for giving me more info.

**Comment by IchigoGames** [comment]
just tested tinyprogressions-1.15.2-4.0.3 and its fixed now ty
