### ISSUE TITLE
[Suggestion] Auto Eject Cobble into adjacent inventories

### ISSUE THREAD

**Issue by davqvist** [Kashdeya/Tiny-Progressions#16]
So I'm thinking about adding Tiny Progressions into my upcoming modpack just to add an alternative to ExU2 cobble gens. But the problem I'm having is that because they don't auto eject into adjacent inventories if I want to use the fastest cobble gen I have to attach for example either EnderIO Conduits with a lot of Speed Upgrades which are expensive or a Transfer node with a lot of speed upgrades to be able to store the generated cobble. But especially if I compare it to the latter option there is no upside in using your cobble gens as I could just use the speed upgrades and make an ExU2 cobble gen. If you don't like a default auto eject, a config option or an upgrade that you could install into the cobble gen would work of course as well. I would appreciate it if you think about that.

**Comment by Kashdeya** [comment]
good idea. something will be in the next update.
