### ISSUE TITLE
Flint armour interacts incorrectly with vanilla armour stand

### ISSUE THREAD

**Issue by Fungidelight** [Kashdeya/Tiny-Progressions#162]
TP version: tinyprogressions-1.15.2-4.0.2.jar
Minecraft version: 1.15.2
Forge version: 31.2.9

Flint armour interacts incorrectly with vanilla armour stand: you can put either boots or leggings onto it but not both, and visually in either case the boots slot looks empty. Chestplate and helmet both work fine.

**Comment by GenDeathrow** [comment]
Will be fixed next update
