### ISSUE TITLE
Charcoal_block recipe

### ISSUE THREAD

**Issue by DrFlash99** [Kashdeya/Tiny-Progressions#163]
1.15 version:
Tiny-Progressions/src/main/resources/data/tp/recipes/charcoal_block.json 

Currently the charcoal_block from TP overwrites the vanilla coal_block recipe by crafting the charcoal block from coal rather then charcoal.

Proposed fix, recipe should use 9 charcoal, rather then 9 coal.

**Comment by GenDeathrow** [comment]
Thanks for the report, will be fixed next update. Not sure how I managed to do that, but its fixed in my dev.
