### ISSUE TITLE
Cobble Generator All Have Same JEI Description(1.15.2-4.0.3)

### ISSUE THREAD

**Issue by ClaudiusMinimus** [Kashdeya/Tiny-Progressions#164]
Tiny Progressions 1.15.2-4.0.3
Minecraft 1.15.2

Two Issues:
- The Emerald and Blaze cobble generators are shown in reverse order in JEI
- The cobble generators all have the same description as seen in the screenshots

![2020-06-15_11 32 53](https://user-images.githubusercontent.com/17887664/84712309-7cc29880-af25-11ea-9475-66c6fc848be8.png)

![2020-06-15_11 32 50](https://user-images.githubusercontent.com/17887664/84712332-85b36a00-af25-11ea-8a39-ec252209cd98.png)

**Comment by GenDeathrow** [comment]
I will take a look at both issues.

**Comment by ArsNotFound** [comment]
There's a fix for this issue in PR #160
