### ISSUE TITLE
Wub hammer crashes server (3.3.34)

### ISSUE THREAD

**Issue by dkbhn** [Kashdeya/Tiny-Progressions#166]
TP version: tinyprogressions-1.12.2-3.3.34.jar
Forge version: 13.23.5.2854

When mining a 3X3 area with Wub hammer, it works fine. but when using oreexcavation, it cashes the server?

An other user says the same thing crashed his Client,

[crash-2020-06-22_18.08.02-server.txt](https://github.com/Kashdeya/Tiny-Progressions/files/4814440/crash-2020-06-22_18.08.02-server.txt)

Hope you can help :)

**Comment by GenDeathrow** [comment]
Version is not maintained atm.
