### ISSUE TITLE
Anvil Crash

### ISSUE THREAD

**Issue by whatthedrunk** [Kashdeya/Tiny-Progressions#168]
Here is an issue submitted from a user that I was able to replicate the same way.

**When attempting to apply an enchantment from an Enchanted Book to some Wither Leggings, the game crashes.**

**Expected Behavior**
The Wither Leggings should be able to have the enchantment applied to them and then removed from the anvil.

**Current Behavior**
Placing the Wither Leggings in an Anvil doesn't crash the game, but adding an Enchanted Book will, thus preventing you from applying the enchantment and crashing the game.

**Steps to Reproduce**
Procure a pair of Wither Leggings from the Tiny Progressions mod and an Enchanted Book (I was using a Protection IV book).
Place the Wither Leggings in an Anvil, and then place the Enchanted Book in.
**Log**
https://gist.github.com/TheWooper/4a939a213f4c0940d19adf64390cc026

https://github.com/AllTheMods/ATM-5/issues/175

**Comment by GenDeathrow** [comment]
I will look into the issue.

**Comment by ArsNotFound** [comment]
There's an error in this [line](https://github.com/Kashdeya/Tiny-Progressions/blob/8e33ec8a67c7b6198cc64b156e2969503ba043d2/src/main/java/com/kashdeya/tinyprogressions/items/materials/ArmorMaterialTier.java#L77). Function getRepairMaterial tries to get uninitialized variable, so NullPointerException is thrown.

**Comment by GenDeathrow** [comment]
Thanks, sorry long work hours.. and this last week has been long.. I see about fixing it  maybe have a fix this weekend.

**Comment by GenDeathrow** [comment]
Sorry the wait on this.. and update is going out today for version 4.0.6 that has the fix for this.
