### ISSUE TITLE
Cobble Gen Crash

### ISSUE THREAD

**Issue by phit** [Kashdeya/Tiny-Progressions#171]
forge 31.2.27
tinyprogressions 1.15.2-4.0.4

crashlog : https://gist.github.com/phit/b105d598869a5dd1a6afe8c8d2b72d96

player said:
>  I shift right clicked a TP cobblestone generator and the server died right then

**Comment by GenDeathrow** [comment]
Believe I had already pushed the update for this and forgot to takes this down.  Should have bee non version 4.0.5
