### ISSUE TITLE
1.15.2 TP Combat config?

### ISSUE THREAD

**Issue by McKitten** [Kashdeya/Tiny-Progressions#172]
The Iron spear, Lapis & Bone armors have competing output targets in my pack and was hoping, given the size of the changes (being able to toggle them individually) that they could get their own config.

Admins also need a way to choose which of the Ender pearl recipes that are available from your dust and I don't see that option available.

Great work so far tho :)

PS Vasholine needs a description in game also.

**Comment by GenDeathrow** [comment]
Configs were changed in 1.15.x for forge. Its now a single flat file (not my choice). As far as changing recipes / toggling items that's all handed via other mods/texture packs now a days.  With the way items are registered now in forge its harder for me to just turn them on and off via configs. I will look into the Vasholine Description though. Thank you.
