### ISSUE TITLE
Growth Crystal Tier 2 Squid Spawns

### ISSUE THREAD

**Issue by kingskybomber14** [Kashdeya/Tiny-Progressions#24]
Pretty fun bug where squids can spawn and live inside the tier two growth crystal. I assume this is because the growth crystal is coded as if it was a block of water. [Imgur link to screenshot](http://imgur.com/a/2Uw8w)

**Comment by GenDeathrow** [comment]
what version are you currently on?

**Comment by kingskybomber14** [comment]
I believe it is 1.0.19? It is whatever Skyfactory 3 version 3.0.6 is using.

**Comment by Kashdeya** [comment]
This has been fixed in the newest update.
