### ISSUE TITLE
Client crash with latest version

### ISSUE THREAD

**Issue by tjsd** [Kashdeya/Tiny-Progressions#26]
Forge: 2221
Java 112
Custom Mod Pack

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Brandon's Core (BrandonsCore-1.10.2-2.1.4.92-universal.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.5.4-beta2-anarchy.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.2.213-universal.jar)
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.8.10.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.10.2-1.0.8.jar)
Contact their authors BEFORE contacting forge

// I feel sad now :(

Time: 2/14/17 10:23 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Tiny Progressions (tp)
Caused by: java.lang.NullPointerException
	at net.minecraftforge.client.model.ModelLoader.setCustomStateMapper(ModelLoader.java:1083)
	at com.kashdeya.tinyprogressions.handlers.RenderHandler.setCustomStateMap(RenderHandler.java:122)
	at com.kashdeya.tinyprogressions.handlers.RenderHandler.preInitBlocks(RenderHandler.java:58)
	at com.kashdeya.tinyprogressions.proxy.ClientProxy.preInit(ClientProxy.java:15)
	at com.kashdeya.tinyprogressions.main.tinyprogressions.preInit(tinyprogressions.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:616)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:624)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:259)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_112, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1294982032 bytes (1234 MB) / 1996488704 bytes (1904 MB) up to 5965348864 bytes (5689 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6400m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2221 63 mods loaded, 63 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2221.jar) 
	UCH	Forge{12.18.3.2221} [Minecraft Forge] (forge-1.10.2-12.18.3.2221.jar) 
	UCH	AdvancedRocketry{1} [Advanced Rocketry] (minecraft.jar) 
	UCH	foamfixcore{7.7.4} [FoamFixCore] (minecraft.jar) 
	UCH	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.2.213-universal.jar) 
	UCH	actuallyadditions{1.10.2-r98} [Actually Additions] (ActuallyAdditions-1.10.2-r98.jar) 
	UCH	libVulpes{0.1.14.20170125231929} [libVulpes] (LibVulpes-1.10.2-0.1.14-universal.jar) 
	UCH	advancedRocketry{1.10.2-1.0.8} [Advanced Rocketry] (AdvancedRocketry-1.10.2-1.0.8.jar) 
	UCH	JEI{3.14.6.408} [Just Enough Items] (jei_1.10.2-3.14.6.408.jar) 
	UCH	appleskin{1.0.5} [AppleSkin] (AppleSkin-mc1.10.2-1.0.5.jar) 
	UCH	Baubles{1.3.9} [Baubles] (Baubles-1.10.2-1.3.9.jar) 
	UCH	bdlib{1.12.2.21} [BD Lib] (bdlib-1.12.2.21-mc1.10.2.jar) 
	UCH	betterbuilderswands{0.11.0} [Better Builder's Wands] (BetterBuildersWands-1.10.2-0.11.0.215+2d66774.jar) 
	UCH	betterquesting{2.3.222} [Better Questing] (BetterQuesting-2.3.222.jar) 
	UCH	guideapi{@VERSION@} [Guide-API] (Guide-API-1.10.2-2.0.2-45.jar) 
	UCH	BloodMagic{1.10.2-2.1.2-71} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.10.2-2.1.2-71.jar) 
	UCH	Botania{r1.9-340} [Botania] (Botania r1.9-340.jar) 
	UCH	CodeChickenLib{2.5.2.213} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.2.213-universal.jar) 
	UCH	brandonscore{2.1.4} [Brandon's Core] (BrandonsCore-1.10.2-2.1.4.92-universal.jar) 
	UCH	Chameleon{1.10-2.2.2} [Chameleon] (Chameleon-1.10-2.2.2.jar) 
	UCH	chisel{MC1.10.2-0.0.8.10} [Chisel] (Chisel-MC1.10.2-0.0.8.10.jar) 
	UCH	crafttweakerjei{1.0.1} [CraftTweaker JEI Support] (CraftTweaker-1.10.2-3.0.20.jar) 
	UCH	MineTweaker3{3.0.20} [MineTweaker 3] (CraftTweaker-1.10.2-3.0.20.jar) 
	UCH	ctgui{1.0.0} [CT-GUI] (CraftTweaker-1.10.2-3.0.20.jar) 
	UCH	eleccore{1.6.379} [ElecCore] (ElecCore-1.10.2-1.6.379.jar) 
	UCH	deepresonance{1.4.5} [DeepResonance] (deepresonance-1.1x-1.4.5.jar) 
	UCH	dimensionalcake{0.0.1} [Dimensional Cake] (dimensionalcake-1.9.4-0.0.1.jar) 
	UCH	draconicevolution{2.0.8} [Draconic Evolution] (Draconic-Evolution-1.10.2-2.0.8.177-universal.jar) 
	UCH	elevatorid{1.3.0} [Elevator Mod] (ElevatorMod[V.1.3.0][MC.1.10.2].jar) 
	UCH	exnihiloadscensio{0.1.5} [Ex Nihilo Adscensio] (exnihiloadscensio-1.10.2-0.1.12.jar) 
	UCH	extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.10.2-1.3.0.jar) 
	UCH	FastLeaveDecay{1.2.3} [Fast Leave Decay] (FastLeaveDecay-MC1.10.2-1.2.3.jar) 
	UCH	foamfix{@VERSION@} [FoamFix] (foamfix-0.5.4-beta2-anarchy.jar) 
	UCH	GardenOfGlass{sqrt(-1)} [Garden of Glass] (GardenOfGlass.jar) 
	UCH	advgenerators{0.9.20.19} [Advanced Generators] (generators-0.9.20.19-mc1.10.2.jar) 
	UCH	gravestone{1.5.12} [Gravestone] (GraveStone Mod 1.5.12.jar) 
	UCH	Harvest{1.10.2-1.1.0-10} [Harvest] (Harvest-1.10.2-1.1.0-10.jar) 
	UCH	inventorysorter{0.10.5+46} [Simple Inventory sorting] (inventorysorter-1.10.2-0.10.5+46.jar) 
	UCH	ironchest{1.10.2-7.0.11.797} [Iron Chest] (ironchest-1.10.2-7.0.11.797.jar) 
	UCH	jeresources{0.5.8.98} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.8.98.jar) 
	UCH	llor{1.1.1-mc[1.9-1.11]} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.1.1-mc[1.9-1.11].jar) 
	UCH	MapWriter{2.6.19} [MapWriter] (MapWriter-1.10.2-2.6.19.jar) 
	UCH	mcmultipart{1.4.0} [MCMultiPart] (MCMultiPart-1.4.0-universal.jar) 
	UCH	mob_grinding_utils{0.1.8.16} [mob_grinding_utils] (MobGrindingUtils-0.1.8.16.jar) 
	UCH	mtlib{@VERSION@} [MTLib] (MTLib-1.0.1.jar) 
	UCH	modtweaker{2.0.9} [Mod Tweaker] (ModTweaker2-2.0.9.jar) 
	UCH	moreshears{1.0.2} [More Shears] (moreshears-1.10.2-1.0.2-release.jar) 
	UCH	Morpheus{1.10.2-3.1.13} [Morpheus] (Morpheus-1.10.2-3.1.13.jar) 
	UCH	mousetweaks{2.6.4} [Mouse Tweaks] (MouseTweaks-2.6.4-mc1.10.2.jar) 
	UCH	Neat{1.3-12} [Neat] (Neat 1.3-12.jar) 
	UCH	oreexcavation{1.2.84} [OreExcavation] (OreExcavation-1.2.84.jar) 
	UCH	questbook{2.1.0-1.10} [Better Questing Quest Book] (questbook-2.1.0-1.10.jar) 
	UCH	StorageDrawers{1.10.2-3.5.17} [Storage Drawers] (StorageDrawers-1.10.2-3.5.17.jar) 
	UCH	refinedstorage{1.2.21} [Refined Storage] (refinedstorage-1.2.21.jar) 
	UCH	rftools{5.83} [RFTools] (rftools-1.1x-5.83.jar) 
	UCH	rftoolscontrol{1.6.6} [RFTools Control] (rftoolsctrl-1.1x-1.6.6.jar) 
	UCH	snad{1.10.2-1.6.09.20a} [Snad] (Snad-1.10.2-1.6.09.20a.jar) 
	UCH	stevescarts{2.1.4.83} [Steve's Carts 2] (StevesCarts-1.10.2-2.1.4.83.jar) 
	UCH	beneath{1.2.0} [The Beneath] (The Beneath-1.10.2-1.2.0.jar) 
	UCH	theoneprobe{1.4.2} [The One Probe] (theoneprobe-1.1x-1.4.2.jar) 
	UCE	tp{1.0.21} [Tiny Progressions] (tinyprogressions-1.10.2-1.0.21.jar) 
	UCH	ts2k16{1.0.3} [Twerk-Sim 2K16] (TS2K16-1.0.3.jar) 
	Loaded coremods (and transformers): 
Brandon's Core (BrandonsCore-1.10.2-2.1.4.92-universal.jar)
  com.brandon3055.brandonscore.asm.ClassTransformer
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.5.4-beta2-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.2.213-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.BlockStateLoaderTransformer
ChiselCorePlugin (Chisel-MC1.10.2-0.0.8.10.jar)
  team.chisel.common.asm.ChiselTransformer
AdvancedRocketryPlugin (AdvancedRocketry-1.10.2-1.0.8.jar)
  zmaster587.advancedRocketry.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 378.49' Renderer: 'GeForce GTX 970/PCIe/SSE2'
	List of loaded APIs: 
		* actuallyadditionsapi (29) from ActuallyAdditions-1.10.2-r98.jar
		* Baubles|API (1.3.1.3) from Baubles-1.10.2-1.3.9.jar
		* BetterQuesting|API (2.6) from BetterQuesting-2.3.222.jar
		* BloodMagic|API (@VERSION@) from BloodMagic-1.10.2-2.1.2-71.jar
		* BotaniaAPI (85) from Botania r1.9-340.jar
		* ChiselAPI (0.0.1) from Chisel-MC1.10.2-0.0.8.10.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.10.2-0.0.8.10.jar
		* CoFHAPI (1.7.10R1.3.1) from BrandonsCore-1.10.2-2.1.4.92-universal.jar
		* CoFHAPI|energy (1.8.9R1.2.0B1) from refinedstorage-1.2.21.jar
		* CoFHAPI|item (1.8.9R1.2.0B1) from mcjtylib-1.1x-2.3.7.jar
		* compatlayer (0.2.2) from compatlayer-1.10-0.2.2.jar
		* DR-API (1.0.4-Beta) from deepresonance-1.1x-1.4.5.jar
		* DraconicEvolution|API (1.3) from Draconic-Evolution-1.10.2-2.0.8.177-universal.jar
		* ElecCoreAPI (1.0) from ElecCore-1.10.2-1.6.379.jar
		* ElecCore|Abilities (#API_VER#) from ElecCore-1.10.2-1.6.379.jar
		* Guide-API|API (1.10.2-2.0.2-45) from Guide-API-1.10.2-2.0.2-45.jar
		* jeresources|API (0.5.8.98) from JustEnoughResources-1.10.2-0.5.8.98.jar
		* JustEnoughItemsAPI (4.10.1) from jei_1.10.2-3.14.6.408.jar
		* MapWriterApi (1.1.0) from MapWriter-1.10.2-2.6.19.jar
		* mcjtylib_ng (2.3.7) from mcjtylib-1.1x-2.3.7.jar
		* stevescartsAPI (2.1.4.83) from StevesCarts-1.10.2-2.1.4.83.jar
		* stevescartsAPI|FARMS (2.1.4.83) from StevesCarts-1.10.2-2.1.4.83.jar
		* StorageDrawersAPI (1.7.10-1.2.0) from refinedstorage-1.2.21.jar
		* StorageDrawersAPI|config (1.7.10-1.2.0) from refinedstorage-1.2.21.jar
		* StorageDrawersAPI|event (1.7.10-1.2.0) from refinedstorage-1.2.21.jar
		* StorageDrawersAPI|inventory (1.7.10-1.2.0) from refinedstorage-1.2.21.jar
		* StorageDrawersAPI|pack (1.7.10-1.2.0) from refinedstorage-1.2.21.jar
		* StorageDrawersAPI|registry (1.7.10-1.2.0) from refinedstorage-1.2.21.jar
		* StorageDrawersAPI|render (1.10.2-1.3.0) from StorageDrawers-1.10.2-3.5.17.jar
		* StorageDrawersAPI|storage (1.7.10-1.2.0) from refinedstorage-1.2.21.jar
		* StorageDrawersAPI|storage-attribute (1.10.2-1.3.0) from StorageDrawers-1.10.2-3.5.17.jar
	CodeChickenLib Invalid Fingerprint Reports:

**Comment by Kashdeya** [comment]
Will be fixed in the next update. 

Thank you

But please next time use pastebin for long crash reports. It makes it easier to read.
