### ISSUE TITLE
The new Growth Crystals have 0 effect.

### ISSUE THREAD

**Issue by jk1895** [Kashdeya/Tiny-Progressions#28]
I just updated your mod but sadly the new growth crystals have ZERO effect on my mystical agriculture crops. Usually they grow like crazy but now nothing! They only produce lots of particles. (BTW, an option to turn the particles of would be cool)
I roled back and eveything is fine again. :-)

**Comment by Kashdeya** [comment]
if you upgrades you might want to delete old config and use the new one. There is nothing that has changed other then how the growth crystals tick. and you will have to change the config to your liking.

**Comment by aaronmallen** [comment]
@Kashdeya because I don't want to open an issue for this and because I can't find the answer freaking anywhere I'll ask here... Does the Y level of the tier 1 growth crystal matter?

**Comment by Kashdeya** [comment]
yes it does. if you are running the newest version the tooltips tell you all about my blocks now.
