### ISSUE TITLE
Tiny progressions isn't respecting the config

### ISSUE THREAD

**Issue by misterfixit** [Kashdeya/Tiny-Progressions#3]
I have disabled a few of the items in the config but they are still registering the items and the crafting recipes are still viable.

**Comment by Kashdeya** [comment]
can you please explain which items, post a screen shot and maybe post the config so that I may see it.

**Comment by misterfixit** [comment]
Sure in-game picture

http://puu.sh/sDkl5.jpg

Config

https://gist.github.com/misterfixit/81b3919a3f5883975e082f82aa2e7a59

**Comment by GenDeathrow** [comment]
I see the issues...

**Comment by GenDeathrow** [comment]
fixed on github, will be fixed on the next build.

**Comment by misterfixit** [comment]
Sweet appreciate it

**Comment by GenDeathrow** [comment]
leaving this opened.. incase someone else reports..

**Comment by GenDeathrow** [comment]
Were waiting on another fix before we push the update out on this one.

**Comment by GenDeathrow** [comment]
this should actually be fixed now on Curse
