### ISSUE TITLE
Growth Crystal affecting Machines (Power usage)

### ISSUE THREAD

**Issue by IonFoXx** [Kashdeya/Tiny-Progressions#31]
Hi,

I updated to the latest version (atm 1.0.21) of Tiny Progression. After the update I experienced high power usage on my Ender IO Farming stations. As it turned out placing the Growth Crystal in range of the Ender IO Machine caused it to use a lot of power. It maxed out my tier one Power Conduits from Ender IO.

I'm not sure if this is intended or if it is a change introduced due to the latest changes to the mod as I didn't experience that behavior before.

Details about the setup:
Normal vanilla Minecraft wheat crops on a 9x9 crop plot. Water block in the center. Above the water is the EnderIO Farming station. The FS is connected to a Power and Item Conduit. The Power Conduit is connected to a Flux Network power plug. The Item Conduit is connected to a Diamond Chest (Iron Chests). The Growth Crystal (Tier I) just needs to be placed close to the FS from EnderIO. Finished the power voiding setup. ;)

Server System:
- Minecraft Version 1.10.2
- Java Version 8
- Windows Server 2012
- Forge 12.18.3.2221

Client System:
- Minecraft Version 1.10.2
- Java Version 8
- Windows 10
- Forge 12.18.3.2221

If there are any other details I can help you with please let me know.

**Comment by GenDeathrow** [comment]
It be impossible for that to happen as this block only affects blocks related to crops/plants. Now Im not an expert on enderio, but does the farming station take RF constantly or only when it actually farms. Cause if its when it farms than you'd us more power cause crops are growing faster. 

Here is the growth crystal code: https://github.com/Kashdeya/Tiny-Progressions/blob/master/src/main/java/com/kashdeya/tinyprogressions/blocks/BlockGrowth.java#L115-L119

**Comment by IonFoXx** [comment]
EnderIO uses constantly power. Even if there is nothing happening. Maybe it's watching the crops and the higher tick rate causes it to use more power. At least that would make sense to me.
But I guess there is not much you or someone from EnderIO could do. So thank you very much for spending your time to analyze that issue!

**Comment by GenDeathrow** [comment]
After looking EnderIO code, it looks like its uses extra RF to perform certain actions. I think we got this figured out so I'm going to go ahead and close this issue.
