### ISSUE TITLE
Cobblegen Crystal Tier 1 Recipy acedently removed?

### ISSUE THREAD

**Issue by drutech** [Kashdeya/Tiny-Progressions#34]
I'm just wondering if the Cobblegen Crystal Tier 1 recipy was acedently removed in version 1.0.22 for Minecrafte 1.10.2.

I have tested it out with only a JEI and Tiny Progression installed. No other mods. Looked up the recipty for the cobbal gen and it's not there. Looked at the config file to see if it's seen set to False by default, but it show true:

    # Enable Cobblegen Crystal Tier 1? [default: true]
    B:"Cobblegen Crystal Tier 1"=true

So I'm thinking either the recipty was turned off in the coading or it thinks it's false in teh config.

Thanks
Drutech

**Comment by Kashdeya** [comment]
it seems to work in my dev workspace and my modpack I test it in.

do you have any screen shots or something. I can look at.

**Comment by drutech** [comment]
here are two screen shoots. I used a crtafting table. No tier 1 cobbal Gen showing.

I added a screen shoot of teh 2 mods.

![capture2](https://cloud.githubusercontent.com/assets/8194773/23097805/c4aa6948-f5fb-11e6-9b82-c9a0587084fa.PNG)
![capture1](https://cloud.githubusercontent.com/assets/8194773/23097806/c4ab787e-f5fb-11e6-9879-b2d369c65860.PNG)
![modslist](https://cloud.githubusercontent.com/assets/8194773/23097823/3b2e6b00-f5fc-11e6-8126-70b0b7bcbcb7.PNG)

**Comment by Kashdeya** [comment]
ok pushing out a fix now. please report back once it gets approved on curse.

**Comment by drutech** [comment]
I though I left a reply that same night. 

Still the same, 

I went back in versions to see when was the last one that had the recipe . It looks like tinyprogressions-1.10.2-1.0.19.jar. I also noticed in the recent ones that Tier 3 is also missing.

**Comment by Kashdeya** [comment]
try deleting your config file and resetting it to a new one.

**Comment by drutech** [comment]
Ok, just checkked and still no. I also went further to see what version had it.  Version 1.10.2-1.0.19 was good after that it stoped having an recipy. Also the the tire 4 is missing an recipy.

**Comment by drutech** [comment]
OK deleted the config file. Still not showeing, I also seen that you are using forge-1.10.2-12.18.3.2185, so I  downgraded to the same Forge version and deleted the conf file again. Still lucking out. Still using teh same tiest setup. JEI and your mod.  Sorry on this.

**Comment by Kashdeya** [comment]
ok Found the problem and will be fixed in next update.
