### ISSUE TITLE
[Suggestion] Change the cobblegen output?

### ISSUE THREAD

**Issue by TheBritishBrotherhood** [Kashdeya/Tiny-Progressions#38]
So im creating a modpack that uses a different cobblestone and i noticed there is no way to change the output of the tiny cobblegens.

Could this possible be implemented in a config option?

Curtis

**Comment by Kashdeya** [comment]
I will not be doing this as all variants of Cobble stone should be oredic to cobblestone. If they are not then the dev of that mod needs to fix that not me.

**Comment by TheBritishBrotherhood** [comment]
I can OreDict the stones, but how would i make it output said stone?

**Comment by Kashdeya** [comment]
if the cobblestone is oredic then you do not need anything else, this means that any type of cobblestone can be used in a recipe. but only if said recipe is also oredic which is also a mod devs issue not mine.

**Comment by TheBritishBrotherhood** [comment]
No what im asking is, Is how i get your cobble generators to output other blocks, in this case <thebetweenlands:betweenStone>

**Comment by vadis365** [comment]
quick answer - you don't
TP cobblegen is for producing vanilla cobble.
BL stone is ore dictionary registered as cobble and stone for use in recipes not for automation in other mod's machines. I help out with both mods and I don't think there are any plans to make either mod do what you want. Maybe at some point in the future some player recipes may be possible to add - but not for the foreseeable future - sorry.

**Comment by TheBritishBrotherhood** [comment]
Okay thats fine :) 

Wont hurt for me to change the texture and name for a quick fix to mask cobblestone.

Appreciate the replies

**Comment by vadis365** [comment]
sure that is the hacky way of making something 
like I said BL stone is ore dictionary registered - I don't see why you cant use normal cobble in recipes as the ore dictionary intended - that is why it exists in the 1st place.

**Comment by TheBritishBrotherhood** [comment]
We can, but were not using any vanilla ores/items, Sorry if i confused you :)

**Comment by vadis365** [comment]
Apparently the ore dict stuff isn't in the release version yet.

**Comment by TheBritishBrotherhood** [comment]
No but it has been added in the dev version :D

**Comment by vadis365** [comment]
Yes.
I know.
I have the code.

**Comment by vadis365** [comment]
Let's close this issue seeing as @Kashdeya doesn't intend to support this feature atm.

**Comment by TheBritishBrotherhood** [comment]
<3
