### ISSUE TITLE
Charcoal Recipe Accepting Stack Size of Zero

### ISSUE THREAD

**Issue by opencma** [Kashdeya/Tiny-Progressions#39]
An empty crafting window returns the charcoal block.

Looks like the recipe got the amount ~~and meta switched~~ wrong.

https://github.com/Kashdeya/Tiny-Progressions/blob/master/src/main/java/com/kashdeya/tinyprogressions/recipes/Recipes.java#L128

**Comment by Kashdeya** [comment]
Just pushed a fix for this, Thank you
