### ISSUE TITLE
Client Only Method

### ISSUE THREAD

**Issue by GenDeathrow** [Kashdeya/Tiny-Progressions#4]
https://github.com/Kashdeya/Tiny-Progressions/blob/master/src/main/java/com/kashdeya/tinyprogressions/blocks/BlockGrowthUpgrade.java#L51

this is a client only method.

**Comment by vadis365** [comment]
It is only called in the client proxy which should keep it client side.
If it's a problem then move it? It's only added so the model won't look for all possible states for the fluid level in the json blockstates file.

**Comment by vadis365** [comment]
If you were going to do it differently you could make the state mapper method in an interface and implement it to your block then call the method with an @SideOnly(Side.CLIENT) annotation.

*Edit - I'll fork the repo later on and make a PR to tidy up the experimental code I sent over to Kash (it has unnecessary casts and stuff in it). It was done 'on the fly' to see if it stopped the crashes.

*Edit2 - urgh! you are using the item model mesher to register your items and item blocks - wai pls? :)

**Comment by GenDeathrow** [comment]
Sorry I missed your comments, I had a fix last night. dark already has a test build.  it was the statemapper that was actually client side only so it would crash on server start when the block init. I just moved it over to only call client side, it should be good now.  Hope you hadn't done anything yet.

**Comment by vadis365** [comment]
No worries - can you push the changes to the repo - you still have some stuff there that I would like to help out with if that is OK?

**Comment by GenDeathrow** [comment]
Yeah I'll get It push later tonight.
