### ISSUE TITLE
Crash with stone armor. 

### ISSUE THREAD

**Issue by woutwoot** [Kashdeya/Tiny-Progressions#40]
When you equip stone armor an error occurs on the server and every time you try to join again you get the error again. Should be easily reproducible. 
Skyfactory 3 modpack 3.0.8
Tiny Progressions 1.0.31

Error:
[http://pastebin.com/r4zCd6fg](http://pastebin.com/r4zCd6fg)

**Comment by Gunner76th** [comment]
Please provide your complete crash report for the mod author. Also please either upload the crash report file, or copy it to pastebin.com or gist here on github. It is not polite to just paste your crash reports in clear text as it causes excessive scrolling to be needed, and in some cases when looking at the report on mobile devices it can be very hard to read and understand.

**Comment by Kashdeya** [comment]
This has been fixed in the newest versions of TP.
