### ISSUE TITLE
Growth Crystal Tier 2 haven't got crafting.

### ISSUE THREAD

**Issue by PanSzelescik** [Kashdeya/Tiny-Progressions#44]
Hello! My English doesn't perfect.
Version: tinyprogressions-1.10.2-1.2.0-Hotfix.jar
Growth Crystal Tier 2 is enabled, but it haven't got crafting. I am deleted old config and I am disabled Emerald tools, because I have Actually Additions. JEI still don't show crafting. Help

**Comment by Kashdeya** [comment]
Make sure you have all the items and blocks enabled in the config for the growth crystal, watering cans, netherstar block, reinforced obsidian.

If you have any of those disabled you will have to make your own recipes as the config files tells you.
