### ISSUE TITLE
[1.11.2] Nether Star Block Missing Localized Name

### ISSUE THREAD

**Issue by Mohron** [Kashdeya/Tiny-Progressions#45]
Mod: tinyprogressions-1.11.2-2.2.0-Hotfix

The Nether star block is missing a localized name.

![image](https://cloud.githubusercontent.com/assets/3623122/24844152/3d53aa96-1d6e-11e7-98d5-06342fa89545.png)

**Comment by Kashdeya** [comment]
Fixed in the next update.
