### ISSUE TITLE
Battle Axe toolClass string

### ISSUE THREAD

**Issue by An-Sar** [Kashdeya/Tiny-Progressions#49]
Could you add a toolClass name to the battle axes? It appears that it is meant to harvest wood, however it does not have a toolClass assigned to it.

The case I have run into is, my mod PrimalCore uses the toolClass strings to decide if a tool is valid for cutting logs or not. If you give it "axe" or even a custom type like "battleaxe", it is very easy for me to add support.

Thank You

**Comment by duncanwebb** [comment]
Please make this enchant as an Axe so that it can be enchanted as an axe - Sharpness V would make it a very useful weapon.

**Comment by duncanwebb** [comment]
When you closed the issue does that mean you have done it or are not going to do it?
