### ISSUE TITLE
Flint armor caused a crash

### ISSUE THREAD

**Issue by FreeTheGamer** [Kashdeya/Tiny-Progressions#50]
I created flint armor and soon as I got it into my inventory I crashed, I can not log back in even after deleting player data. Here is the issue in the log.

https://pastebin.com/i3HCXi7Y

**Comment by momocow** [comment]
Use MCEdit to delete the armor from your player's slot can save your account. I have the same issue on the stone armor while my TP version is 1.1.0.

**Comment by Kashdeya** [comment]
will look into this during next update.
