### ISSUE TITLE
[1.11.2] Cascading WorldGen

### ISSUE THREAD

**Issue by Lordmau5** [Kashdeya/Tiny-Progressions#52]
![img](https://i.lordmau5.com/1498935291-10972.png)

It seems the only thing this mod is generating is the Ender Ore, so that is what I have now disabled.

Googled a bit around, found a good thread explaining it:
https://www.reddit.com/r/feedthebeast/comments/5x0twz/investigating_extreme_worldgen_lag/

**Proposal:**
Expand upon `WorldGenMineable` instead of implementing the `IWorldGenerator` interface and go from there, as stated in the Reddit post.

**Comment by Kashdeya** [comment]
what version of the mod are you using?

**Comment by Lordmau5** [comment]
`2.2.1-Hotfix`.

I noticed there's a new version, `2.2.3`, but the changelog interestingly enough doesn't mention anything in regards to this.
Neither is your source code up-to-date so I could've checked in advance.

**Comment by Kashdeya** [comment]
fixed in latest release.
