### ISSUE TITLE
Cobblegen name conflict with SimpleUpgrades

### ISSUE THREAD

**Issue by ghost** [Kashdeya/Tiny-Progressions#6]
I was trying out some new mods and discovered that both SimpleUpgrades and Tiny Progressions introduce an item called cobblegen_block. 

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Tiny Progressions (tp)
Caused by: java.lang.IllegalArgumentException: Duplicate id: tileEntityCobblegen

Would you consider refactoring the name or including a config to completely disable the item? (sucobblegen or tp cobblegen?)

**Comment by Kashdeya** [comment]
There is a config option to disable the cobblegen and everything else in both of my mods. you will have to uninstall one or the other to load the configs and disable what ever you do not want.

With that being said if you are installing Simple Upgrades there is really no reason to use Tiny Progressions seeing that almost everything in TP is in Simple Upgrades with the exception of a few little things that are only there for the modpack the mod was made for.

**Comment by vadis365** [comment]
Hello,
I'm being nosy again :P 
This can be fixed pretty easily by just adding your mod's name as a prefix to the TE which would then make it unique and solve any conflicts.
Here is an example from one of my mods if it helps :)

https://github.com/vadis365/Mob-Grinding-Utils/blob/master/MobGrindingUtils/MobGrindingUtils/src/main/java/mob_grinding_utils/proxy/CommonProxy.java#L26

It may remove existing TE's in peoples worlds tho' :(
Cheers,
Me.
