### ISSUE TITLE
Cobblestone Generator problem.

### ISSUE THREAD

**Issue by Gloruzhark** [Kashdeya/Tiny-Progressions#68]
Hello. I was playing Lite Island modpack and i have issue with Cobble generator. When i place the generator ontop of vanilla Hopper which is sitting on Storage Drawer my game crashes. Anyway to fix this? 
Edit: It is happening even with tranfer nodes for EU2
Here is crash report:
https://docs.google.com/document/d/1sK1A1Q7cpqItrlQkwZ0WIdLLfWe9tXxH_gXYkIBOJow/edit?usp=sharing

**Comment by Kashdeya** [comment]
This has been fixed, and will be in the next update.
