### ISSUE TITLE
[1.12.1] Server Crash on Start

### ISSUE THREAD

**Issue by YOYOK9** [Kashdeya/Tiny-Progressions#70]
Server Crash on startup.

MC: 1.12.1
TP: 1.12-3.2.7 - Beta
Forge: 1.12.1-14.22.1.2485

Crash:
https://pastebin.com/ZCWqYA5w

**Comment by mcdodge34** [comment]
I've got this exact same problem, prepared to upgrade my server to latest versions of every mod, the client starts fine and plays fine, but if I try to launch my test server, I get this crash, here's my log if it can help you out : https://pastebin.com/meAdn5uZ

Ninja edit : even test with 3.2.9 beta, same results, I got back to 3.2.6 for now.

**Comment by ghost** [comment]
I believe this has now been fixed by commit 01958fe9e6db277e1bb410f40cc933380b15500d; requesting @Kashdeya to verify and release a build.

Once the fixes have been verified, I will work on fixing all remaining mods that have been broken by my changes of late.

**Comment by ghost** [comment]
Tiny Progressions 3.2.10 Beta is now live on CurseForge: 
https://minecraft.curseforge.com/projects/tiny-progressions/files/2489292;
 it fixes several things broken in earlier versions, including mip-map rendering bugs and server crashes.
