### ISSUE TITLE
Crash when harvesting with a Scythe

### ISSUE THREAD

**Issue by EnderCorpsAlpha** [Kashdeya/Tiny-Progressions#71]
Hi, Using version 3.2.6 of the mod on 1.12.1, When breaking a 3x3 area of mystical agriculture plants when the scythe (any tier) when it's close to breaking, It crashes my client, I'll attach the crash log below:
https://pastebin.com/1pqiffta

**Comment by Kashdeya** [comment]
should be fixed in newest release
