### ISSUE TITLE
(Feature Request) Configurable Stats for Food, Armor, Tools and Weapons?

### ISSUE THREAD

**Issue by Vaygrim** [Kashdeya/Tiny-Progressions#75]
I love BIG stretches of "Tiny Progressions" right now, but there is a small corner of it that just breaks the power curve for the rest of the mod.. as well as almost every other mod in my mod pack at present. Baked Apples and most of the 'Sandwich' food items have ridiculous amounts of saturation to them. Baked Apples alone have a Saturation rating of 64 and only require an Oak Tree and a furnace. Obsidian Armor, Tools and Weapons also really have some amazing stats for being so easy to obtain within the first in-game day or two. Coming this with the Ender Dragon and Wither centered armor sets and Tiny Progression edges out past every other mod I've got in my pack with longer and deeper tech tree progression in them.

What are the odds that we could maybe see some config settings that would let mod pack creators ... 'adjust' the stats on these items slightly?

**Comment by Kashdeya** [comment]
will be adding new configs to newest versions. release coming soon.
