### ISSUE TITLE
Cooked Apples OP Saturation

### ISSUE THREAD

**Issue by alexsch01** [Kashdeya/Tiny-Progressions#76]
Hi when you cook apples in a furnace you get cooked apples (in MC 1.12.x). This is super OP because a cooked apple gives you 64x saturation (maybe it was supposed to be 6 hunger notches?!). Can you please fix this issue?

Version: tinyprogressions-1.12-3.2.10 - Beta.jar
MC Version: 1.12.2
Forge Version: 2568

**Comment by Kashdeya** [comment]
this will be fixed later down the road in a update. Thank you
