### ISSUE TITLE
Battleaxes cant get sword enchantments

### ISSUE THREAD

**Issue by N1ch0l2s** [Kashdeya/Tiny-Progressions#77]
I was wondering, since the name implies they're weapons, how come they can't get any sword enchantments such as Sharpness? If the reason is because they have fast attack speeds, then that makes sense. But it would be nice if they could get sword enchantments even if they couldn't get Sweeping Edge. I don't know any other Battleaxe stats besides the Obsidian's because it seems to be the strongest and fastest.

**Comment by Kashdeya** [comment]
fixed in dev space
