### ISSUE TITLE
crash report when having the latest compile commit

### ISSUE THREAD

**Issue by JoeSGT** [Kashdeya/Tiny-Progressions#79]
hello i had compile this commit https://github.com/Kashdeya/Tiny-Progressions/commit/903eb22b6c3c420f02d6b953051de98202545e1c
and i had crash because of this line
https://github.com/Kashdeya/Tiny-Progressions/blob/1.12.2/src/main/java/com/kashdeya/tinyprogressions/registry/InternalRegistry.java#L195
with having Extra Utilities version 1.12-1.7.2

**Comment by JoeSGT** [comment]
Forgot to add the crash report https://pastebin.com/Dye1E2C2

**Comment by GenDeathrow** [comment]
Actually I believe its coming from this section of code.
https://github.com/Kashdeya/Tiny-Progressions/blob/1.12.2/src/main/java/com/kashdeya/tinyprogressions/registry/InternalRegistry.java#L209-L236

 I'm not sure if its some how passing a null Ore Dictionary name, but vanilla forge handles nulls properly if its passed to register ore dictionary. So Im not sure what it is passing atm. 


I cant test this atm.. cause Im heading into work. but hopfully someone else will get on it.

**Comment by Kashdeya** [comment]
we are hoping this has been fixed in our dev space. but FYI out commits to github are not always going to work if compiled. we use github as a backup for end of day coding. so there is always going to be bugs and errors and issues with out commits when compiled.
