### ISSUE TITLE
Ender ore crashes game when mined by alternative methods

### ISSUE THREAD

**Issue by Kudan7** [Kashdeya/Tiny-Progressions#80]
MC Version: 1.12.2

ways it crashed from explosions (efln from tinkers) and from being quarried (RFtools builder quarry), the explosions let me still enter the world but if it was quarried it locks the world unable to re enter it again.

sadly no crash report was formed when this happened to my knowledge.

**Comment by Kashdeya** [comment]
looking into issues for next update.

**Comment by GenDeathrow** [comment]
Strange.. I have no idea what would cause that.

**Comment by Kudan7** [comment]
Yeah i had to go through many test just to make sure it was that and not a different mod.

could the spawning of the endermite when mined be partial of the issue?

**Comment by Kashdeya** [comment]
yes it could be. you might want to turn off the endermites and see if it still crashes. but idk why that would cause the issue unless we have to put in a player check for them to spawn for fake players and mines/quarries do not spawn them.

we will do some testing and see if we can come up with anything. but i think that might be the case.

**Comment by Kudan7** [comment]
weird, i made a folder and ran a test with just those mods mentioned and no issue came up, both with the endermite set to true and false. though when this issue came up in the modpack i was playing, the issue didnt go away until i disabled ender ore entirely. so the conflict might be with something else, though dont know what. want me to post the modlist where the issue occurred?

**Comment by Kashdeya** [comment]
Closing for now as we can not reproduce the issue.
