### ISSUE TITLE
Big Pouch Crashing

### ISSUE THREAD

**Issue by Blazkin** [Kashdeya/Tiny-Progressions#81]
I keep getting crashed when opening up the big pouch in ATM3 i added your mod as there are multiple items i like 

I also kept getting crashed when i had plants enabled

**Comment by Kashdeya** [comment]
Sorry but we can not help you. That is a premade pack and we do not give support for packs that are made by pack Devs. 

Pack devs make each pack different and if you go adding mods to a already prebuilt pack there is no promise that it will work the way you want it too. 

However if you ever decide to make your own pack and still run into issues please let us know. It is also faster if you join our discord as we give faster support there then here.
