### ISSUE TITLE
Pouch is still crashing. 

### ISSUE THREAD

**Issue by Kashdeya** [Kashdeya/Tiny-Progressions#82]
we need to look into this a little better once we have a stable devspace. 

crash report. 

[crash-2018-01-18_02.11.28-client.txt](https://github.com/Kashdeya/Tiny-Progressions/files/1641501/crash-2018-01-18_02.11.28-client.txt)

**Comment by GenDeathrow** [comment]
I think I have a  fix for it. Will push it up soon.

**Comment by GenDeathrow** [comment]
https://github.com/Kashdeya/Tiny-Progressions/pull/84

**Comment by Kashdeya** [comment]
fixed
