### ISSUE TITLE
Crashes After I Add Mod

### ISSUE THREAD

**Issue by Avakining** [Kashdeya/Tiny-Progressions#86]
[crash-2018-01-29_18.06.04-client.txt](https://github.com/Kashdeya/Tiny-Progressions/files/1675605/crash-2018-01-29_18.06.04-client.txt)
It does not crash if I don't use this mod, and the above crash happens if I do.

**Comment by Kashdeya** [comment]
update Tiny Progressions. 3.2.6 is a older version

https://minecraft.curseforge.com/projects/tiny-progressions/files?filter-status=1&filter-game-version=2020709689%3A6756
