### ISSUE TITLE
Moving items around in the Pouch crashes the client

### ISSUE THREAD

**Issue by laconicdesigns** [Kashdeya/Tiny-Progressions#88]
I tried moving a stack of cobblestone around in the pouch, and it crashes my client. Same happens when you try and drop something from the bag by dragging it outside of the gui.

[crash-2018-02-03_19.44.36-client.txt](https://github.com/Kashdeya/Tiny-Progressions/files/1692350/crash-2018-02-03_19.44.36-client.txt)

**Comment by Kashdeya** [comment]
Has been fixed in dev workspace and will be in the next update.
