### ISSUE TITLE
NPE:Ticking Player

### ISSUE THREAD

**Issue by Zeevian** [Kashdeya/Tiny-Progressions#93]
Build 1.12.2.3.3.23
Forge: 1.12.2-14.23.2.2631

[crash-2018-03-20_10.50.17-client.txt](https://github.com/Kashdeya/Tiny-Progressions/files/1829827/crash-2018-03-20_10.50.17-client.txt)

When using an activated watering can.  Happens with both watering cans.

Tested using only Tiny Progressions.

**Comment by Ozzymud** [comment]
Same thing I believe while trying to stress test Millenaire NPCs. Using reinforced can to water their maze causes ticking... https://pastebin.com/BwkXkjJz

Figured a second crash log couldn't hurt.
