### ISSUE TITLE
Wub gem Paxel crashing when use on non vanilla grass type block

### ISSUE THREAD

**Issue by scalda** [Kashdeya/Tiny-Progressions#95]
HI, we are having these crashes with the Wub paxel where it will crash you to desktop when mining non-vanilla grass type block.

[crash-2018-04-17_13.38.37-client.txt](https://github.com/Kashdeya/Tiny-Progressions/files/1919559/crash-2018-04-17_13.38.37-client.txt)
[crash-2018-04-17_13.00.13-client.txt](https://github.com/Kashdeya/Tiny-Progressions/files/1919560/crash-2018-04-17_13.00.13-client.txt)

Forge: forge-1.12.2-14.23.3.2664
TP: tinyprogressions-1.12.2-3.3.25-Release
MC: 1.12.2

Any help would be great

**Comment by Kashdeya** [comment]
This has been fixed in the next update.

**Comment by scalda** [comment]
ok sweet thank you,

any time frame til release?
