### ISSUE TITLE
Invalid shapeless ore recipe: juicer, null, 1xtile.air@0

### ISSUE THREAD

**Issue by JWTHDYTWA** [Kashdeya/Tiny-Progressions#98]
Game simply crashes on loading. Here's [crashlog](https://gist.github.com/Warrock3280/2201eb6da7feb5d20887a40da8a656ec).

**Comment by Warrock3280** [comment]
It could happened after some config edits.

**Comment by ghost** [comment]
Something I get as it has something to do with the Extra.cfg and disabling something in there
